### ISSUE TITLE
file-finder breaks with latest less

### ISSUE THREAD

**Issue by lottspot** [ZECTBynmo/file-finder#3]
``` node
uncaughtException: Cannot read property 'contents' of undefined
  at Object.Parser.parse (/home/james/node_modules/hatchjs/node_modules/less/lib/less/parser/parser.js:117:20)
  at /home/james/node_modules/hatchjs/app/models/Stylesheet.js:118:20
  at /home/james/node_modules/hatchjs/node_modules/async/lib/async.js:119:25
  at /home/james/node_modules/hatchjs/node_modules/async/lib/async.js:24:16
  at /home/james/node_modules/hatchjs/app/models/Stylesheet.js:104:21
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:71:17
  at /home/james/node_modules/hatchjs/node_modules/file-finder/file-finder.js:81:16
  at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by ZECTBynmo** [comment]
I seriously doubt this is the file-finder's fault, because it only deals with filenames. Do you have some kind of hook that automatically compiles less files when they're scanned? What is Stylesheet.js?

**Comment by lottspot** [comment]
I'll carry this issue over to hatchjs, which is the project in this case actually utilizing file-finder. It looks like hatchjs is all but unmaintained at this point, so all signs point to you being right on this one. I'll close this thing out
